### ISSUE TITLE
Helm chart doesn't allow setting allowedTopologies for storage class.

### ISSUE THREAD

**Issue by camaeel** [sergelogvinov/proxmox-csi-plugin#114]
### Description

Storage class here: https://github.com/sergelogvinov/proxmox-csi-plugin/blob/main/charts/proxmox-csi-plugin/templates/storageclass.yaml doesn't allow defining/redefining allowedTopologies.
It would be great to have this possibility to manage hybrid clusters

**Comment by sergelogvinov** [comment]
Hi, it in my wish list... 
Thanks.

**Comment by camaeel** [comment]
@sergelogvinov I added a PR to add topologies to helm chart
