### ISSUE TITLE
GRPC error: failed to get region for node

### ISSUE THREAD

**Issue by dark4rest** [sergelogvinov/proxmox-csi-plugin#116]
### Description
Pods don't starting.

### Logs
I1207 07:40:14.628978       1 identity.go:38] GetPluginInfo: called
I1207 07:40:16.200038       1 node.go:469] NodeGetInfo: called with args {}
E1207 07:40:16.205850       1 main.go:119] GRPC error: failed to get region for node k8s01
### Environment
clusters:
  - url: https://10.0.0.10:8006/api2/json
    insecure: true
    token_id: "kubernetes-csi@pve!csi"
    token_secret: "secret_tocken"
    region: home01

- Plugin version:

- Kubernetes version: [`kubectl version --short`]
Client Version: v1.26.11
Kustomize Version: v4.5.7
Server Version: v1.26.11

**Comment by sergelogvinov** [comment]
Hello `failed to get region for node k8s01`
Probably it cannot find the node in proxmox. kubernetes node name should be the same as proxmox VM name.

Please check the node providerID, nodename etc. Do you use ProxmoxCCM ?
`kubectl describe node ...`

**Comment by dark4rest** [comment]
k8s01 - VM's name. Name of proxmox node is different. I have 3 VM's for kubernetes cluster on 1 Proxmox node. How i use CSI in this configuration?

**Comment by sergelogvinov** [comment]
> k8s01 - VM's name. Name of proxmox node is different. I have 3 VM's for kubernetes cluster on 1 Proxmox node. How i use CSI in this configuration? I don't use ProxmoxCCM

CSI uses labels - topology.kubernetes.io/region,topology.kubernetes.io/zone to define node properties. https://github.com/sergelogvinov/proxmox-csi-plugin#proxmox-vm-config

**Comment by dark4rest** [comment]
I added labels topology.kubernetes.io/region and topology.kubernetes.io/zone to all nodes. Pods are starting. But controller pod is in pending status with "0/3 nodes are available: 3 node(s) didn't match Pod's node affinity/selector. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling.."
