### ISSUE TITLE
Update the documentation with the latest features

### ISSUE THREAD

**Issue by remipcomaite** [sergelogvinov/proxmox-csi-plugin#184]
### Description
It seems that the documentation is not up to date with the latest features.
I am talking in particular about the use of shared storage like Ceph.
It also seems that the roadmap is not up to date in the README.
Will this be updated soon?

**Comment by sergelogvinov** [comment]
Nice catch, thank. Yep, readme is outdated.

Probably, better to create issues as roadmap. 

Thanks.
