### ISSUE TITLE
better support shared block devices

### ISSUE THREAD

**Issue by sergelogvinov** [sergelogvinov/proxmox-csi-plugin#185]
## Feature Request

Better support shared block devices.

### Description

It is not properly tested. So we need to make a lab and check everything.
* move pvc between nodes
* add/delete proxmox nodes

**Comment by MisderGAO** [comment]
Hello, 
Is this feature going to be supported? I tried iscsi storage, it does not work.

**Comment by sergelogvinov** [comment]
Hi, please create an issue and share more details. 

I've did not try iscsi, but it should work.

**Comment by sergelogvinov** [comment]
was done [#202](https://github.com/sergelogvinov/proxmox-csi-plugin/pull/202)
