### ISSUE TITLE
bug in helm chart 0.2.7?

### ISSUE THREAD

**Issue by camaeel** [sergelogvinov/proxmox-csi-plugin#242]
### Description

I installed helm-chart version 0.2.7 and controller pods started to crash.

### Logs

Controller: [`kubectl logs -c proxmox-csi-plugin-controller proxmox-csi-plugin-controller-...`]

```
proxmox-csi-controller-fc496759b-77mzn proxmox-csi-controller flag provided but not defined: -metrics-address
```

Node: [`kubectl logs -c proxmox-csi-plugin-node proxmox-csi-plugin-node-...`]

### Environment

- Plugin version:
- Kubernetes version: v1.30.3
- CSI capasity: [`kubectl get csistoragecapacities -ocustom-columns=CLASS:.storageClassName,AVAIL:.capacity,ZONE:.nodeTopology.matchLabels -A`]
- CSI resource on the node: [`kubectl get CSINode <node> -oyaml`]
- Node describe: [`kubectl describe node <node>`]
- OS version [`cat /etc/os-release`]

**Comment by sergelogvinov** [comment]
yep, its sad story #239

**Comment by camaeel** [comment]
Sorry, I was in a hurry and forgot to check if it was reported in closed tickets.
