### ISSUE TITLE
Microk8s compatible

### ISSUE THREAD

**Issue by Cheety** [sergelogvinov/proxmox-csi-plugin#282]
### Description

<img width="1271" alt="dwad" src="https://github.com/user-attachments/assets/0788b502-8a28-4e2a-954c-2d4253ec0959">

can you please implement auto creation for microk8s volume path?

### Community Note

* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request

**Comment by sergelogvinov** [comment]
Hello, you need to change one value in helm chart like:

```
kubeletDir: /var/snap/microk8s/common/var/lib/kubelet
```

**Comment by sergelogvinov** [comment]
Add to docs: https://github.com/sergelogvinov/proxmox-csi-plugin/pull/283
