### ISSUE TITLE
Change block size of filesystem

### ISSUE THREAD

**Issue by travuga77** [sergelogvinov/proxmox-csi-plugin#62]
## Feature Request
Possibility to change block size on creating filesystem
### Description
How can I change block size on a xfs filesystem from 4K to 1K? We store mostly very small files and we want to avoid wasting of space.

**Comment by sergelogvinov** [comment]
Hello, currently, plugin does not support it. 
It looks like feature request. 

As an option you can create PVC, scale down the pods, and re-format this disk with additional options manually.
